packages:
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@parcel/watcher@2.5.6'
  - esbuild
  - esbuild@0.28.1
  - nx
  - sharp
  - sharp@0.34.5
  - workerd
  - workerd@1.20260708.1

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.3.3

overrides:
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

blockExoticSubdeps: false

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260714.1'

allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  nx: true
  sharp: set this to true or false
  workerd: set this to true or false
